web_app/shopwindow/urls.py
from django.urls import path
from shopwindow.views import *

from myshop.views import HomeView, UserCreateView, UserCreateDoneTV

app_name = 'shopwindow'

urlpatterns = [
    #/product
    path('',ProductLV.as_view(),name= 'index'),
    #/<product:id>
    path('<int:pk>', ProductDV.as_view(), name='detail'), 

    path('accounts/', include('django.contrib.auth.urls')), 
    
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),



]

web_app/client/models.py
from django.db import models

# Create your models here.

web_app/shopwindow/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField(default=0)
    description = models.CharField(max_length=5000)
    #image
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.name
        
    def get_absolute_url(self): # 현재 데이터의 절대 경로 추출
        return '' # reverse('blog:post_detail', args=(self.slug,))
    
    def get_previous(self): # 이전 데이터 추출
        return self.get_previous_by_modify_dt()

    def get_next(self): # 다음 데이터 추출
        return self.get_next_by_modify_dt()

web_app/client/views.py
from django.shortcuts import render

# Create your views here.

web_app/myshop/views.py
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

#--- Homepage
class HomeView(TemplateView):
 template_name = 'home.html'

#--- User Creation
class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')
    
class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

web_app/shopwindow/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from shopwindow.models import Product


# Create your views here.
class ProductLV(ListView):
    model = Product
    paginate_by = 2

class ProductDV(DetailView):
    model = Product

web_app/shopwindow/templates/shopwindow/product_detail.html
<!DOCTYPE html>
<html lang="kr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    {{ object.name }}
    {{ object.price }}
    {{ object.description }}
    {{ object.quantity }}
</body>

</html>

web_app/shopwindow/templates/shopwindow/product_list.html
<h1>hihihi</h1>
{% for product in object_list %}
<a href = "{% url 'shopwindow:detail' product.id %}">
    <div class="container">
        <h3>{{product.name}}</h3>
        <h3>{{product.price}}</h3>
        <h3>{{product.description}}</h3>
    </div>
</a>
{% endfor %}
<div>
    <span>
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">Prev</a>
        {% endif %}
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}
        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">Next</a>
        {% endif %}
    </span>
</div>